name: Potential Duplicates
on:
  issues:
    types: [opened, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: potential duplicate
          exclude: |
            icons
            icon
            logos
            logo
            adding
            add
            requesting
            request
          state: all
          threshold: 0.7
          comment: |
            This issue is potentially a duplicate of one of the following issues:
            {{#issues}}
              - [#{{ number }}] {{ title }} ({{ accuracy }}%)
            {{/issues}}
